In [3]:
import pandas as pd
import pickle
import numpy as np
import json

In [4]:
with open('/home/klb807/MARS_project/MABe24/annotation_data/processed_keypoints.json', 'rb') as fid:
    json_list = json.load(fid)

In [19]:
df['ann_black'].values[0].keys()
# for value in df['ann_black'].values:
    # print(value['area'])

dict_keys(['X', 'Y', 'bbox', 'med', 'geom_med', 'mu', 'std', 'area'])

In [54]:
with open('/home/klb807/MARS_project/MABe24/detection/priors_brown_top.pkl', 'rb') as fid:
    # df = pd.DataFrame(pickle.load(fid))
    arr = np.array([item for item in pickle.load(fid)])

print(arr)

[[array([0.03801714]) array([0.]) array([0.08698286]) array([0.125])]
 [array([0.03273959]) array([0.]) array([0.09226041]) array([0.125])]
 [array([0.0272818]) array([0.]) array([0.0977182]) array([0.125])]
 ...
 [array([0.5]) array([0.58667354]) array([1.]) array([0.91332646])]
 [array([0.5]) array([0.62632334]) array([1.]) array([0.87367666])]
 [0.025000000000000022 0.025000000000000022 0.975 0.975]]


/home/klb807/miniconda3/envs/mars_dev/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


for some reason a lot of rows are arrays of arrays.
I'm not sure whether that's a good thing or not...

In [57]:
# change every row to arrays of array
arr_arr = arr.copy()

for i_row in range(arr_arr.shape[0]):
    for i_col in range(arr_arr.shape[1]):
        if type(arr_arr[i_row,i_col]) is not np.ndarray:
            arr_arr[i_row, i_col] = np.expand_dims(np.array([arr_arr[i_row, i_col]]),0)

# for i_col in range(arr_arr.shape[1]):
#     arr_arr[-1,i_col] = np.expand_dims(arr_arr[-1,i_col], 0)

print(arr_arr)

with open('/home/klb807/MARS_project/MABe24/detection/priors_black_top_all_array.pkl', 'wb') as fid:
    pickle.dump(arr_arr, fid)

[[array([0.03801714]) array([0.]) array([0.08698286]) array([0.125])]
 [array([0.03273959]) array([0.]) array([0.09226041]) array([0.125])]
 [array([0.0272818]) array([0.]) array([0.0977182]) array([0.125])]
 ...
 [array([0.5]) array([0.58667354]) array([1.]) array([0.91332646])]
 [array([0.5]) array([0.62632334]) array([1.]) array([0.87367666])]
 [array([[0.025]]) array([[0.025]]) array([[0.975]]) array([[0.975]])]]


In [4]:
# now just pull all of the items out of lists
arr_flat = arr.copy()

for i_row in range(arr_flat.shape[0]):
    for i_col in range(arr_flat.shape[1]):
        if type(arr_flat[i_row,i_col]) is np.ndarray:
            arr_flat[i_row, i_col] = arr_flat[i_row, i_col][0]

print(arr_flat)

with open('/home/klb807/MARS_project/MABe24/detection/priors_black_top_flat_arr.pkl', 'wb') as fid:
    pickle.dump(arr_arr, fid)

[[0.039795399061034575 0.0 0.08520460093896542 0.125]
 [0.032746697791163036 0.0 0.09225330220883697 0.12499999999999999]
 [0.025227506072559497 0.0 0.0997724939274405 0.125]
 ...
 [0.5 0.6197503458445962 1.0 0.8802496541554037]
 [0.5 0.6516498415045198 1.0 0.8483501584954802]
 [0.025000000000000022 0.025000000000000022 0.975 0.975]]


In [21]:
with open('/home/klb807/Downloads/priors_black_top.pkl', 'rb') as fid:
    arr = np.array([item for item in pickle.load(fid)])

print(arr)

FileNotFoundError: [Errno 2] No such file or directory: '/home/klb807/Downloads/priors_black_top.pkl'